### ISSUE TITLE
Using a Brace mode causes Uncaught Type Error

### ISSUE THREAD

**Issue by intrepidOlivia** [securingsincity/react-ace#583]
# Problem

I've been getting some mysterious errors in the "uncontrolled" mode of my Code Editing component built with AceEditor. It happens in an anonymous function and doesn't provide much information. I've narrowed it down to see that it occurs when I pass in a `mode` prop to the Ace Editor. But I can't decipher it further than that.

My dependencies:
```
"brace": "0.11.1",
"react": "16.4.2",
"react-ace": "6.3.2",
```

The exact text of the error is this:

```
index.js:18058 {message: "Uncaught TypeError: Cannot read property 'substring' of undefined", data: undefined, file: "blob:http://localhost:8070/e57cc920-a648-4d98-b50a-056519dcb0b7", line: 1, col: 9574, …}col: 9574data: undefinedfile: "blob:http://localhost:8070/e57cc920-a648-4d98-b50a-056519dcb0b7"line: 1message: "Uncaught TypeError: Cannot read property 'substring' of undefined"stack: "TypeError: Cannot read property 'substring' of undefined↵    at exports.applyDelta (blob:http://localhost:8070/e57cc920-a648-4d98-b50a-056519dcb0b7:1:9574)↵    at Document.applyDelta (blob:http://localhost:8070/e57cc920-a648-4d98-b50a-056519dcb0b7:1:21858)↵    at Array.<anonymous> (blob:http://localhost:8070/e57cc920-a648-4d98-b50a-056519dcb0b7:1:26690)↵    at Sender.EventEmitter._signal (blob:http://localhost:8070/e57cc920-a648-4d98-b50a-056519dcb0b7:1:10664)↵    at window.onmessage (blob:http://localhost:8070/e57cc920-a648-4d98-b50a-056519dcb0b7:1:3542)"__proto__: Object
reportError @ index.js:18058
onMessage @ index.js:18049
16:05:05.710 blob:http://localhost:8070/e57cc920-a648-4d98-b50a-056519dcb0b7:1 Uncaught TypeError: Cannot read property 'substring' of undefined
    at exports.applyDelta (blob:http://localhost:8070/e57cc920-a648-4d98-b50a-056519dcb0b7:1)
    at Document.applyDelta (blob:http://localhost:8070/e57cc920-a648-4d98-b50a-056519dcb0b7:1)
    at Array.<anonymous> (blob:http://localhost:8070/e57cc920-a648-4d98-b50a-056519dcb0b7:1)
    at Sender.EventEmitter._signal (blob:http://localhost:8070/e57cc920-a648-4d98-b50a-056519dcb0b7:1)
    at window.onmessage (blob:http://localhost:8070/e57cc920-a648-4d98-b50a-056519dcb0b7:1)
exports.applyDelta @ blob:http://localhost:8070/e57cc920-a648-4d98-b50a-056519dcb0b7:1
applyDelta @ blob:http://localhost:8070/e57cc920-a648-4d98-b50a-056519dcb0b7:1
(anonymous) @ blob:http://localhost:8070/e57cc920-a648-4d98-b50a-056519dcb0b7:1
EventEmitter._signal @ blob:http://localhost:8070/e57cc920-a648-4d98-b50a-056519dcb0b7:1
window.onmessage @ blob:http://localhost:8070/e57cc920-a648-4d98-b50a-056519dcb0b7:1
```

Here's a repro case:

### Component:
```
import React, { Component } from 'react';
import AceEditor from 'react-ace';
import 'brace/mode/json';

export default class CodeEditor2 extends Component {
	constructor(props) {
		super(props);
		this.state = {
			codeValue: props.value || '',
		};
		this.updateValue = this.updateValue.bind(this);
	}

	updateValue(value) {
		this.setState({
			codeValue: value,
		});
		this.props.onChange && this.props.onChange(value);
	}

	render() {
		const { value, onChange, ...aceProps } = this.props;

		return (
			<div>
				<AceEditor
					onChange={this.updateValue}
					value={value || this.state.codeValue}
					{...aceProps}
				/>
			</div>
		);
	}
}
```

### Container:
```
import React, { Component } from 'react';
import CodeEditor2 from "../../../src/components/code_editor/code_editor_2";

export default class Sandbox extends Component {
	constructor(props) {
		super(props);
		this.state = {
			codeValue: '{}',
		};
		this.onCodeChange = this.onCodeChange.bind(this);
	}

	onCodeChange(value) {
		this.setState({
			codeValue: value,
		});
	}

	render() {
		return (
			<div>
				<CodeEditor2
					onChange={this.onCodeChange}
					value={this.state.codeValue}
					mode="json"
				/>
			</div>
		);
	}
}
```

I've spent hours trying to figure out what I'm doing wrong, and just can't figure it out. Is this a bug?

**Comment by intrepidOlivia** [comment]
If someone else can try my repro for me and see if they get the same result? I just need verification of whether it's a bug or user error.

**Comment by intrepidOlivia** [comment]
@securingsincity or @chentsulin Could I possibly get a repro from one of you? If you have a quick dev environment to throw the above code into.

**Comment by tyler-cloud-elements** [comment]
I was also was seeing the same issue on `mode="json"` when I was performing a re-parse on the JSON in the render method

```
    const formattedValue = mode === 'json' && isJsonString(value) ? JSON.stringify(JSON.parse(value), null, 2) : value;
```

**Comment by nodejh** [comment]
I have the same issue.

**Comment by jarodhanko** [comment]
I had the same issue.  It seemed to be expecting newlines or something like that.  If I created an ace editor with `mode='json'` and seed the data with `'{\n \n}'` it wouldn't break until I cleared it out completely and tried to type `{` `enter`

**Comment by PrimeObjects** [comment]
Any fix to it?

**Comment by AdriOliveira** [comment]
Same issue here, any updates?

**Comment by xdrblog** [comment]
had fixed?

**Comment by AdriOliveira** [comment]
> had fixed?

For me the problem was my onChange method was trying to read a value which I wasn't providing

**Comment by hamoody-omar** [comment]
Any update on that? I am still getting the same error

**Comment by securingsincity** [comment]
I think this is resolved in `v8.0.0` I can't reproduce this is on the diff site anymore

**Comment by hesto2** [comment]
I can verify that this resolved the issue. Just upgraded from version 7 to version 8 and am no longer getting the error.

**Comment by securingsincity** [comment]
thanks @hesto2

**Comment by vadim-shilov** [comment]
> I had the same issue. It seemed to be expecting newlines or something like that. If I created an ace editor with `mode='json'` and seed the data with `'{\n \n}'` it wouldn't break until I cleared it out completely and tried to type `{` `enter`

I still catching this error! It reproduces when `onChange` handler is declared.
mode: json
react-ace: ^9.1.1

**Comment by Uyarn** [comment]
> > I had the same issue. It seemed to be expecting newlines or something like that. If I created an ace editor with `mode='json'` and seed the data with `'{\n \n}'` it wouldn't break until I cleared it out completely and tried to type `{` `enter`
> 
> I still catching this error! It reproduces when `onChange` handler is declared.
> mode: json
> react-ace: ^9.1.1

still catch this error as well. react-ace:^8.0.0, mode:json

**Comment by mvitkin** [comment]
I am having the same issue when using worker-json from ace-builds. Has anyone found a solution?

react-ace: 9.3.0
ace-builds: 1.4.12

As mentioned, this issue only arises when `onChange` is defined in `AceEditor`.

Uncaught TypeError: Cannot read property 'substring' of undefined

**Comment by yashaswinibprasad87** [comment]
> I had the same issue. It seemed to be expecting newlines or something like that. If I created an ace editor with `mode='json'` and seed the data with `'{\n \n}'` it wouldn't break until I cleared it out completely and tried to type `{` `enter`

I am facing same issue . Any fixes found? Kindly update

**Comment by vipulDessai** [comment]
The issue is reproducible in case there are multiple states updates without a time gap inside the onChange function using with mode as `JSON`
```javascript
// changing from this code
const onChange = codeEditorOutput => {
    if ((!codeEditorOutput && !jsonCodeColumnData.IsNullable) || (codeEditorOutput && !commonUtility.isValidJson(codeEditorOutput))) {
        setDisableSave(true);
    }
    else {
        setDisableSave(false);
    }

    setValue(codeEditorOutput);
}

// to this (introducing a timeout) fixed my issue
const onChange = codeEditorOutput => {
    // the timeout is used because updating the states simultaneously causes the 
    // ace editor to break and show invalid syntax error
    clearTimeout(onChangeTimeoutRef.current);
    onChangeTimeoutRef.current = setTimeout(() => {
        if ((!codeEditorOutput && !jsonCodeColumnData.IsNullable) || (codeEditorOutput && !commonUtility.isValidJson(codeEditorOutput))) {
            setDisableSave(true);
        }
        else {
            setDisableSave(false);
        }
    }, 500);

    setValue(codeEditorOutput);
}
```

**Comment by markLaxus** [comment]
I fixed mine by setting default to '{}'

newValue  = ( newValue  !== '') ? newValue  : '{}';

**Comment by brycefranzen** [comment]
Is there a solution to this yet? I'm still having this issue on version `10.1.0`

The issue appears to occur on keypress of `return` or `enter` with type `json`

**Comment by livyk** [comment]
I found the way how to fix similar problem with react-hook-form. The main problem is the react-hook-form state (or any external state) and AceEditor state (internal state) became out of sync after onChange. When onChange happened, AceState already have new value, but external state (value prop) can't update for a few renders and still equal to previous value. This is cause of the error.
So that's how I fixed it.

```jsx
export function AceAdapter({ field: { value, onChange } }) {
  const [lastStringValue, setLastStringValue] = useState(value)

  const handleChange = useCallback((newValue) => {
    setLastStringValue(newValue)
    onChange(newValue)
  }, [onChange])

  useEffect(() => {
    setLastStringValue(value)
  }, [value])

   return (
      <AceEditor
         value={lastStringValue}
         onChange={handleChange}
       />
    )
}
```
